name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.12.0'
          channel: 'beta'

      - run: flutter config --enable-web
      - run: flutter clean
      - run: flutter pub get
      - run: flutter build web --release --web-renderer html --base-href /MMAMobile/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build/web
          force_orphan: true
          user_name: 'ajtemir'
          user_email: 'ajtemirulanbekuulu@gmail.com'
          commit_message: 'Publish to gh-pages'
